repos:
  - repo: local
    hooks:
      - id: create-requirements
        name: create-requirements
        entry: ls -a
        language: system
        always_run: true
        pass_filenames: false