repos:
  - repo: local
    hooks:
      - id: create-requirements
        name: create-requirements
        entry: "./create-requirements.sh"
        language: system
        always_run: true
        pass_filenames: false